[package]
name = "match_game"
version = "0.1.0"
authors = ["Sungmin Han <kenneth@pigno.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = "0.6.1"
